In [21]:
import numpy as np
import plotly.graph_objects as go

In [26]:
def sigmoid(x):
    return 1/(1+(1/(np.power(np.e,x))))

def relu(x):
    return np.maximum(0,x)

In [23]:
from graph_support import before_func

In [24]:
@before_func(title = "シグモイド関数",x_name= "input",y_name= "output")
def plot_func(x_data,y_data,graph):
    fig = graph.fig
    fig.add_trace(
            go.Scatter(
                x=x_data,
                y=y_data,
                name = "計測点",
                mode='markers',
                opacity=0.8,
            )
        )
    fig.update_layout(
        legend=dict(
            x=1.2,
            y=0.5,
           
            traceorder="normal",
            font=dict(
                size=12,
            ),
        ),
    )
    fig.show()

In [27]:
x_array = np.linspace(-10,10,100)
y_array = np.array([sigmoid(i) for i in x_array])
y_array_relu = np.array([relu(i) for i in x_array])


In [29]:
plot_func(x_data = x_array,y_data = y_array)

In [28]:
plot_func(x_data = x_array,y_data = y_array_relu)

配列の計算

In [33]:
# 1次元
A = np.array([1,2,3,4])
print(A.ndim)
print(A.shape[0])

1
4


In [34]:
# 2次元
B = np.array([[1,2],[3,4],[5,6]])

print(B.ndim)
print(B.shape[0])

2
3


In [35]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [36]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [39]:
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])

np.dot(X,W)


array([ 5, 11, 17])

 Neuralのモデル化

In [41]:
X = np.array([1.0,0.5])
W = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B = [0.1,0.2,0.3]

A = np.dot(X,W) + B
Z1 = sigmoid(A)

In [43]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = [0.1,0.2]
A2 = np.dot(Z1,W2)+B2 

In [46]:
Z2 = sigmoid(A2)

In [47]:
Z2

array([0.62624937, 0.7710107 ])

In [48]:
def identify_function(x):
    return x

In [49]:
W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])
A3 = np.dot(Z2,W3)+ B3
Y = identify_function(A3)

In [50]:
Y

array([0.31682708, 0.69627909])

この関数が分類問題の出力関数になる

In [51]:
def soft_max(a:np.array):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    return exp_a/sum_exp_a
