In [8]:
import numpy as np

逆伝播法のロジック試作

In [9]:
class MulLayer(object):
    def __init__(self):
        self.x = None
        self.y = None
    def forward(self,x,y):
        self.x = x
        self.y = y
        return x*y
    
    def backward(self,signal):
        dx = signal * self.y
        dy = signal * self.x
        return dx,dy

class AddLayer(object):
    def __init__(self):
        pass
    def forward(self,x,y):
        return x+y
    
    def backward(self,signal):
        dx = signal *1
        dy = signal *1
        return dx,dy

入力変数設定

In [10]:
apple_price = 100
apple_num = 2
mandarin_price = 150
mandarin_num = 3
tax = 1.1

使用するインスタンス作成

In [11]:
apple_mul = MulLayer()
mandarin_mul = MulLayer()
fruits_add = AddLayer()
price_mul = MulLayer()

forward

In [12]:
total_apple_price = apple_mul.forward(apple_price,apple_num)
total_mandarin_price = mandarin_mul.forward(mandarin_price,mandarin_num)
fruits_price = fruits_add.forward(total_apple_price,total_mandarin_price)
total = price_mul.forward(fruits_price,tax)
print(total)

715.0000000000001


backforward

In [13]:
feed_back_signal = 1

In [15]:
d_fruits_price,d_tax = price_mul.backward(feed_back_signal)
d_apple_total_price,d_mandarin_total_price = fruits_add.backward(d_fruits_price)
d_apple_num,d_apple_price = apple_mul.backward(d_apple_total_price)
d_mandarin_num,d_mandarin_price = mandarin_mul.backward(d_mandarin_total_price)

print(d_tax)
print(d_apple_num)
print(d_apple_price)
print(d_mandarin_num)
print(d_mandarin_price)

650
2.2
110.00000000000001
3.3000000000000003
165.0


In [18]:
x = np.array([[0.81,2],[-0.1,-3]])
mask = x<=0
x[mask] = 0
x

array([[0.81, 2.  ],
       [0.  , 0.  ]])

In [2]:
import numpy as np

In [5]:
x_dot_w = np.array([[0,0,0],[10,20,30]])
b = np.array([[1,2,3]])
x_dot_w+b

array([[ 1,  2,  3],
       [11, 22, 33]])

In [17]:
np.array([[1,2,3]]).ndim

2

In [15]:
np.array([1,2,3]).ndim

1

In [7]:
np.array([[1,2,3]]) == np.array([1,2,3])

array([[ True,  True,  True]])